[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "DamageMeter"
description = "Toggle to enable/disable a damage meter with 'F5'."
websiteUrl = "https://github.com/Little-Sparroh/DamageMeter"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/DamageMeter.dll"
target = "BepInEx/plugins/DamageMeter.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


